[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/:token"
  to = "/index.html"
  status = 200
